# app name: historictrentobot
# url: https://historictrentobot.appspot.com

entrypoint: gunicorn -b :$PORT main:app
runtime: python37

# gcloud config list project
# gcloud config set project historictrentobot
# gcloud app deploy -q -v test/production
