name: deploy-app-to-gcp
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml -q -v production
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.DEPLOY_NOTIFICATION_WEBHOOK_URL_PRODUCTION }}
          webhook_secret: ${{ secrets.DEPLOY_NOTIFICATION_WEBHOOK_SECRET }}

# DEPLOY_NOTIFICATION_WEBHOOK_URL_OIST should be
# https://<env_name>.<google_project>.appspot.com/<DEPLOY_NOTIFICATION_WEBHOOK_URL_ROUTING>